server:
  port: 8080
spring:
  zipkin:
    base-url: http://192.168.56.100:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: business-account
  data:
    redis:
      host: 192.168.56.100
      port: 6379
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/business?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

seata:
  tx-service-group: SEATA_GROUP
  service:
    vgroup-mapping:
      SEATA_GROUP: default

mybatis:
  mapper-locations: classpath:mapper/*mapper.xml

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign:
            debug
          sleuth:
            debug